image: node:12.16.1

stages:
  - lint
  - tests
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm install

lint:
  stage: lint
  script:
    - npm run lint

tests:
  stage: tests
  script:
    - npm run test:coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 3 days

publish_npm_production:
  stage: deploy
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
  only:
    - master
    - publish-npm-production

pages:
  stage: deploy
  dependencies:
    - tests
    - lint
  script:
    - npm run build
    - npm run build-storybook
    - npm run test:coverage
    - ls -lah .
    - echo $PUBLIC_TOKEN
    - mkdir -p public/$PUBLIC_TOKEN
    - mv storybook-static/ public/$PUBLIC_TOKEN/docs
    - mv coverage/ public/$PUBLIC_TOKEN/
    - mv lib public/$PUBLIC_TOKEN/
    - mv stats.html public/$PUBLIC_TOKEN/
  artifacts:
    paths:
      - public/
      - coverage/
    expire_in: 30 days
  only:
    - master
    - deploy-pages
  allow_failure: true
