image: node:stable

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm install

lint:
  stage: test
  script:
    - npm run lint

tests:
  stage: test
  script:
    - npm run test:coverage

publish:
  stage: deploy
  script:
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm run publish
  only:
    - production

storybook:
  stage: deploy
  script:
    - npm run build-storybook
  only:
    - production